# Generated by Django 6.0.1 on 2026-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
